[package]
name = "notetaking_app_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
candid = "0.10.4"
ic-cdk = "0.17.2"
ic-cdk-macros = "0.8.0"  # <-- update this to match candid 0.10.x
